# Site settings
author: Bryan Capitulo
title: The Road to UX Engineering
header-img: img/home-bg.png
email: bryancapitulo@gmail.com
copyright_name: Bryan Capitulo
description: > # this means to ignore newlines until "baseurl:"
  Why I chose the Software Engineering as a path to UX
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  BryanChapter

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
